# Generated by Django 5.2.13 on 2026-04-12 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('rating', models.FloatField(default=4.0)),
                ('delivery_time', models.CharField(default='30-40 min', max_length=50)),
                ('price_for_two', models.CharField(default='₹500 for two', max_length=100)),
                ('category', models.CharField(default='Mixed', max_length=100)),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('offers', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
